### ISSUE TITLE
Initial Setup Complete

### ISSUE THREAD

**Issue by TDManning** [CCirbo/Little_Shop#3]
Check [here](https://curriculum.turing.edu/module2/projects/little_shop/back_end_requirements) for full instructions

- [x] Invite Collaborators
- [ ] Rails New
- [x] SimpleCov
- [x] Download & Move pgdump File to Directory Under DB/Data
- [x] Add Text From Kickoff Page to Seeds File
- [x] rails db:{drop,create,migrate,seed}
- [ ] rails db:schema:dump

**Comment by CCirbo** [comment]
This is complete
